version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_HOST: db
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  cypress:
    build:
      context: .
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./cypress/evidence:/e2e/cypress/evidence
      - ./cypress/e2e:/e2e/cypress/e2e
    networks:
      - app-network

  jmeter:
    build:
      context: ./jmeter
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./jmeter/results:/tests/results
    environment:
      - TEST_PLAN=simple-load-test.jmx
      - USERS=5
      - RAMP_TIME=10
      - HOST=backend
      - PORT=4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
